### ISSUE TITLE
Upgrade activejdbc-gradle-plugin to latest release 1.5

### ISSUE THREAD

**Issue by cschabl** [javalite/activejdbc-gradle#10]
Use latest release 1.5 of active-jdbc-gradle-plugin.

**Comment by cschabl** [comment]
@ipolevoy , as long as the API `org.javalite.instrumentation.Main` isn't changed, there is no more need to update the activejdbc-gradle-plugin or to change its configuration after a release of ActiveJDBC.
You just update the version of the activejdbc.jar in the compile dependencies of the project and the plugin will use the corresponding activejdbc-instrumentation.jar.

**Comment by ipolevoy** [comment]
it did not and not likely to change any time soon.
