### ISSUE TITLE
Error on building gradle

### ISSUE THREAD

**Issue by VinsoyTisoy** [javalite/activejdbc-gradle#4]
Hi, im trying to instrument my models in my Android app. But there is an error.

`:clean UP-TO-DATE
:app:clean
:compileJava NO-SOURCE
:instrumentModels
**************************** START INSTRUMENTATION ****************************
Directory: C:\Users\vadin\AndroidStudioProjects\ActiveJDBForAndroidTest\build\classes\java\main
:instrumentModels FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrumentModels'.
> java.io.FileNotFoundException: C:\Users\vadin\AndroidStudioProjects\ActiveJDBForAndroidTest\build\classes\java\main\activejdbc_models.properties (The system cannot find the path specified)`

It is true that the file doesn't exist. But I also dont know why the directory is equal to that path. Can anyone help me ? Im new to gradle.

**Comment by ipolevoy** [comment]
Please, configure your project as the working Gradle example: 
https://github.com/javalite/activejdbc-gradle

that should help

**Comment by VinsoyTisoy** [comment]
Yeah, i followed the Gradle example but still it doesnt work.

Here is the error:

`**************************** START INSTRUMENTATION ****************************
Directory: C:\Users\vadin\AndroidStudioProjects\TestJDBC\build\classes\java\main
:instrumentModels FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrumentModels'.
> java.io.FileNotFoundException: C:\Users\vadin\AndroidStudioProjects\TestJDBC\build\classes\java\main\activejdbc_models.properties (The system cannot find the path specified)`

**Comment by VinsoyTisoy** [comment]
I am trying to implement ActiveJDBC to Android since its fast and easy to use.

**Comment by ipolevoy** [comment]
can you please see what is different between your project and a working example with Gradle? If the sample works and your project does not, there must be a difference in config.

**Comment by ipolevoy** [comment]
also, directory: `C:\Users\vadin\AndroidStudioProjects\ActiveJDBForAndroidTest\build\classes\java\main` is strange, don't you think?

**Comment by VinsoyTisoy** [comment]
@ipolevoy I solved this issue by using stand alone instrumentation temporarily because my main goal is to connect sqlite database using active jdbc. Will try some other time.

**Comment by ipolevoy** [comment]
:+1:
