### ISSUE TITLE
Upgrade ActiveJDBC dependencies to 2.3.1-j8

### ISSUE THREAD

**Issue by cschabl** [javalite/activejdbc-gradle#8]
Upgrade ActiveJDBC dependencies in build.gradle to new released version 2.3.1-j8. (s. [activejdbc-gradle-plugin, issue 7](https://github.com/cschabl/activejdbc-gradle-plugin/issues/7))

**Comment by ipolevoy** [comment]
:+1:

**Comment by cschabl** [comment]
@ipolevoy , a question not directly related to this issue: 
I contributed PRs to your [javalite project](https://github.com/javalite/javalite) and this project. I'm listed as contributor at the latter one but not at this one. Why?

**Comment by cschabl** [comment]
Ok, I have to star this repository.

**Comment by ipolevoy** [comment]
@cschabl this might have caused some confusion, but the merging of ActiveJDBC and ActiveWeb repos happened in this order: 

1. I **renamed** `activejdbc` repo to `javalite`
2. I merged all history of `activeweb` repo into `javalite` repo
3. Post-merge cleanup

As a  result,  your `activejdbc` fork now points to `javalite` repo (formerly known as `activejdbc`)

I hope this helps!
